name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            omneedia/storage
          tags: |
            type=raw,value=1.0.0
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max